### ISSUE TITLE
ES5 compilation

### ISSUE THREAD

**Issue by Poyoman39** [fjorgemota/jimple#25]
Hi guys,

I sadly discovered that Jimple is not compatible with "create-react-app". It make the build fail with the following error : 

> Failed to minify the code from this file:
>
>        ./node_modules/jimple/src/Jimple.js:45
>
> Read more here: http://bit.ly/2tRViJ9

Any idea about how to fix it ?

**Comment by homer0** [comment]
@Poyoman39 The problem is that it's requiring the version on the `src` folder, which is not ES5. A quick fix that may work is instead of doing `require('jimple')`, change it to `require('jimple/dist/Jimple.js')`.

Now, the weird thing is that `create-react-app` uses webpack, and from [the documentation](https://webpack.js.org/configuration/resolve/#resolve-mainfields) and my own experience (I use Jimple + webpack quite a lot), webpack automatically knows whether to use the ES5 or ES6+ version. Maybe `create-react-app` is doing something weird behind the curtains :P.

I hope this helps!

**Comment by Poyoman39** [comment]
Nice ! Thank you it fixed my problem 👍  ... it will be cleaner than puting the jimple.js file in my src folder :D

**Comment by fjorgemota** [comment]
Hey.

Sorry for the delay in the answer.

@Poyoman39 was the `resolve.mainFields` correctly configured on your webpack config? I'm a bit curious for what happened on your project.

By the way, thank you all for using this project. =)

**Comment by Poyoman39** [comment]
Hey :)

Sorry for the delay of my answer too  ;)

Since i'm using create-react-app the webpack configuration is hidden ... and i've no idea about how it may looks like :D 

Maybe this may help you : i'm using this version of "react-scripts": "1.1.0" which contains hidden all the webpack config. As i can see inside the webpack files of this node module, there is no trace about any "mainFields"

Hope this helps you :)

By the way too ... thanks for sharing this nice project, and make ioc simple ;)

**Comment by fjorgemota** [comment]
Oh. I see.

Well, okay then, it's good that you resolved the problem. =)

And you're welcome! Feel free to open new issues if you have doubts, problems or suggestions. )
