### ISSUE TITLE
Async create strange behavior

### ISSUE THREAD

**Issue by Poyoman39** [fjorgemota/jimple#56]
I used to user async function as instance providers, as is :

```js
ioc.set('conf', async() => { return someInstance });
```

When i use it inside a REACT project, it's working fine, but not when i use it on server side. It may be due to babel or webpack compilation.

What about adding support for async function ? I wrote a small pull request which should do the job (not tested)

**Comment by fjorgemota** [comment]
Yeah, you're right, `babel` would probably rewrite your async function so it appears as a normal function to Jimple, because of polyfills and a few rewrites made by [regenerator](https://facebook.github.io/regenerator/).

Because of this, personalyl I don't have problems with adding support for async functions. I'll review your PR soon.

**Comment by fjorgemota** [comment]
Closed by #57.
