### ISSUE TITLE
Why ?

### ISSUE THREAD

**Issue by avighier** [fjorgemota/jimple#7]
Why to make hundred the same things in NPM ?

I have written https://github.com/avighier/simple-dijs begin 2015, why to write the same 1000 times ?

I don't understand the work, the time we can spend is for nothing ?? Can you help me to understand ??

Have a good day.

**Comment by fjorgemota** [comment]
Well, let's list some options:

1. For **studying**. Jimple is developed fully in ES6, a technology that I have never "touched" before;
2. For **options**, I implemented Jimple as an port to [Pimple](http://pimple.sensiolabs.org/) to anyone coming from the PHP world. What's not your case;
3. For **using in browser**, Jimple can be used in browsers, so creating isomorphic code is easy, I think;
4. Because **I'm free**, in my country and in NPM there's nothing saying that I cannot do something that...well, I can. Well, of course, as long I do not break the laws..(but container dependency injection is not copyrighted, right?);
5. Because **I can**, as long I can develop and I do not break any laws, I do not see why I will not develop a thing **I WANT** to develop;

Well, I think that the last two items of the list basically resume all the power of freedom. The first three, however, show that your library is definetely not the same as Jimple. 

I already contributed to many libraries in my life, like [Rickshaw](https://github.com/shutterstock/rickshaw/pull/403), [Meteor Transactions](https://github.com/JackAdams/meteor-transactions/issues/47) and some other opttions available here in Github. I created forks of (and rewritten entire) projects, too, like [MatrUFSC2](http://matrufsc2.appspot.com), for projects that was abandoned (in this case, [MatrUFSC](http://ramiro.arrozcru.org/matrufsc)), and...well, when I create some library or project, is because I can. That's opensource, that's the right to be free, and you can do nothing against it as long you contribute to opensouce.

Just accept it, contribute more, and let the people do what they want to do. You're not so special as you feel when opening that issue and it's not because you feel like doing the same thing of anothers you cannot work more do to a better work than these people, and because of that pillar that npm and any opensource project works, and works so well. :)

By final, I end with some links of successful projects that works well and have been implemented in different ways to do the same thing, something you call like "write the same 1000 times". Because of these projects we have a better web, with better support to new technologies and a well formed community:

- [UnderscoreJS](http://underscorejs.org/) -> [Lodash](http://lodash.com);
- [npm](https://github.com/npm/npm) -> [yarn](https://github.com/yarnpkg/yarn);

That's it.

Have a good day, too.

**Comment by avighier** [comment]
Fernando, thanks for speed answer. It was an opened question, as I wrote I would like to understand, know your point of view. What you say it's interesting, I am thinking about that.

Regards

**Comment by fjorgemota** [comment]
Hey.

I really think that's a great discussion. No problems about that.

Any questions...well, just ask. :)

Regards.
